# These are supported funding model platforms

github: [khrystoph]
custom: ['bretwards.eth', 'https://commerce.coinbase.com/checkout/59b5bf4b-5b45-44fd-8cdc-bdb3cc00bf92', 'DNKVNSBUagGq12mNFdGssFkzmJKbjRz1yz', 'bc1qmu6m0ajwk7qy64h5l6km5uze6rzuzycmfuv36q']
